{
 "title": "Solar Power Plant",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Home", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Inverters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "pv_real_kw{inverter=\"0\"}",
     "legendFormat": "Inverter 0"
    },
    {
     "expr": "pv_real_kw{inverter=\"1\"}",
     "legendFormat": "Inverter 1"
    },
    {
     "expr": "pv_real_kw{inverter=\"2\"}",
     "legendFormat": "Inverter 2"
    },
    {
     "expr": "pv_real_kw{inverter=\"3\"}",
     "legendFormat": "Inverter 3"
    },
    {
     "expr": "pv_real_kw{inverter=\"4\"}",
     "legendFormat": "Inverter 4"
    },
    {
     "expr": "pv_real_kw{inverter=\"5\"}",
     "legendFormat": "Inverter 5"
    },
    {
     "expr": "pv_real_kw{inverter=\"6\"}",
     "legendFormat": "Inverter 6"
    },
    {
     "expr": "pv_real_kw{inverter=\"7\"}",
     "legendFormat": "Inverter 7"
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 7, "x": 14, "y": 1 } },
  {
   "title": "Cell Temp / Weather",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pv_cell_temp_c", "legendFormat": "__auto" },
    {
     "expr": "(weather_sunny_flag * day_flag) + day_flag",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GHI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "Wm2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "solar_ghi_wm2{source=\"file\"}",
     "legendFormat": "GHI"
    }
   ]
  },
  {
   "title": "Model Accuracy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_accuracy_pct", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 7, "x": 0, "y": 9 },
   "targets": [
    { "expr": "sum(pv_ideal_kw)", "legendFormat": "Ideal" },
    { "expr": "sum(pv_real_kw)", "legendFormat": "Simulated" }
   ]
  },
  {
   "title": "Absolute Error",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 7, "x": 7, "y": 9 },
   "targets": [
    { "expression": "$A - $B", "type": "math" }
   ]
  },
  {
   "title": "PR",
   "type": "status-history",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 9 },
   "targets": [
    { "expr": "plant_pr_daily", "legendFormat": "Daily PR" }
   ]
  },
  {
   "title": "Panel Title",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 13 },
   "targets": [
    { "expr": "plant_pr_inst", "legendFormat": "instant PR" }
   ]
  },
  { "title": "Inverters Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Inverter 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"0\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"0\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 21 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"1\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"1\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 21 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"2\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"2\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 3",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"3\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"3\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 4",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"4\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"4\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 5",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"5\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"5\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 6",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"6\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"6\"}",
     "legendFormat": "real"
    }
   ]
  },
  {
   "title": "Inverter 7",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
   "targets": [
    {
     "expr": "pv_ideal_kw{inverter=\"7\"}",
     "legendFormat": "ideal"
    },
    {
     "expr": "pv_real_kw{inverter=\"7\"}",
     "legendFormat": "real"
    }
   ]
  }
 ]
}